import pytest
from datetime import datetime, timedelta, timezone
from dal.jobs import JobRepository
from models import Job, JobStatus, Worker
from db import check_connection, get_connection # Added this line
import threading

# Mark all tests in this file as 'integration' and skip if DB is not available
try:
    db_available = check_connection(max_retries=1, delay_sec=1)
except Exception:
    db_available = False

pytestmark = pytest.mark.skipif(not db_available, reason="database not available for integration tests")


@pytest.fixture
def job_repo() -> JobRepository:
    """Provides a JobRepository instance for testing."""
    return JobRepository("jobs_test")

@pytest.fixture
def sample_worker() -> Worker:
    """Provides a sample Worker object."""
    return Worker(
        worker_id="test-worker-1",
        worker_type="cpu", # Changed from "transcription" to a valid worker_type
        machine_alias="test-machine-alias",
        hostname="test-machine"
    )

@pytest.fixture
def sample_job() -> Job:
    """Provides a sample Job object."""
    return Job(
        # job_id will be generated by default_factory
        job_type="transcription",
        ytid="test_ytid_123",
        media_path="/path/to/test/media.mp4", # Added media_path
        status=JobStatus.PENDING,
        config={"model": "medium", "language": "en"}
    )

class TestJobRepository:
    def test_create_and_get(self, job_repo: JobRepository, sample_job: Job):
        """
        Tests that a job can be created and then retrieved by its job_id.
        """
        # Create a job
        created_job = job_repo.create(sample_job)

        assert created_job is not None
        assert created_job.job_id is not None # job_id should be auto-generated
        assert created_job.job_type == sample_job.job_type
        assert created_job.ytid == sample_job.ytid
        assert created_job.status == sample_job.status
        assert created_job.config == sample_job.config

        # Retrieve the job
        retrieved_job = job_repo.get(created_job.job_id)

        assert retrieved_job is not None
        assert retrieved_job.job_id == created_job.job_id
        assert retrieved_job.job_type == created_job.job_type
        assert retrieved_job.ytid == created_job.ytid
        assert retrieved_job.status == created_job.status
        assert retrieved_job.config == created_job.config
        assert retrieved_job.created_at is not None
        assert retrieved_job.updated_at is not None

    def test_claim_next_single_worker(self, job_repo: JobRepository, sample_job: Job, sample_worker: Worker):
        """
        Test that a single worker can claim a pending job.
        """
        # Create a pending job
        created_job = job_repo.create(sample_job)
        assert created_job.status == JobStatus.PENDING

        # Worker claims the job
        claimed_job = job_repo.claim_next(sample_worker)
        
        assert claimed_job is not None
        assert claimed_job.job_id == created_job.job_id
        assert claimed_job.status == JobStatus.CLAIMED
        assert claimed_job.claimed_by == sample_worker.worker_id
        assert claimed_job.claimed_at is not None

        # Verify that the job is no longer pending in the DB
        retrieved_job = job_repo.get(created_job.job_id)
        assert retrieved_job.status == JobStatus.CLAIMED
        assert retrieved_job.claimed_by == sample_worker.worker_id

    def test_claim_next_stale_job_reclaiming(self, job_repo: JobRepository, sample_worker: Worker):
        """
        Test that claim_next reclaims stale jobs.
        """
        # 1. Create a job and claim it
        job = job_repo.create(Job(
            job_type="transcription", ytid="stale-job", media_path="/path/stale.mp4",
            status=JobStatus.PENDING, priority=0
        ))
        
        claimed_job_initial = job_repo.claim_next(sample_worker)
        assert claimed_job_initial.status == JobStatus.CLAIMED
        assert claimed_job_initial.claimed_by == sample_worker.worker_id

        # 2. Manually set updated_at to a past timestamp to make it stale
        with get_connection() as conn:
            with conn.cursor() as cur:
                # Set updated_at to 2 hours ago so the lease appears expired
                stale_time = datetime.now(timezone.utc) - timedelta(hours=2)
                cur.execute(
                    f"UPDATE {job_repo.table_name} SET updated_at = %s WHERE job_id = %s",
                    (stale_time, job.job_id)
                )
            conn.commit()

        # 3. Another worker (or the same one) tries to claim a new job
        # Since no new jobs, it should reclaim the stale one
        reclaimed_job = job_repo.claim_next(sample_worker)

        assert reclaimed_job is not None
        assert reclaimed_job.job_id == job.job_id # Should reclaim the same job
        assert reclaimed_job.status == JobStatus.CLAIMED # Still claimed, but by the new attempt
        assert reclaimed_job.claimed_by == sample_worker.worker_id
        assert reclaimed_job.claimed_at is not None


    def test_claim_next_concurrency(self, job_repo: JobRepository):
        """CRITICAL: Test that SELECT FOR UPDATE SKIP LOCKED prevents double-claims"""
        # Create 5 pending jobs
        jobs = []
        for i in range(5):
            job = Job(
                job_type="transcription",
                ytid=f"test-{i}",
                media_path=f"/path/to/media_{i}.mp4", # Required media_path
                status=JobStatus.PENDING
            )
            jobs.append(job_repo.create(job))

        # Simulate 3 workers claiming simultaneously
        claimed_jobs = []
        lock = threading.Lock()

        def claim_as_worker(worker_id_str):
            worker = Worker(
                worker_id=worker_id_str,
                worker_type="cpu", # Valid worker_type
                machine_alias=f"test-machine-alias-{worker_id_str}", # Required
                hostname=f"test-machine-{worker_id_str}"
            )
            claimed = job_repo.claim_next(worker)
            with lock:
                claimed_jobs.append(claimed)

        threads = [
            threading.Thread(target=claim_as_worker, args=(f"worker-{i}",))
            for i in range(3)
        ]

        for t in threads:
            t.start()
        for t in threads:
            t.join()

        # Verify: 3 different jobs claimed, no duplicates
        claimed_ids = [j.job_id for j in claimed_jobs if j]
        assert len(claimed_ids) == 3
        assert len(set(claimed_ids)) == 3  # No duplicates

        # Verify remaining jobs are still pending
        remaining_jobs = [j for j in jobs if j.job_id not in claimed_ids]
        assert len(remaining_jobs) == 2
        for job in remaining_jobs:
            retrieved_job = job_repo.get(job.job_id)
            assert retrieved_job.status == JobStatus.PENDING

    def test_claim_next_prioritization(self, job_repo: JobRepository, sample_worker: Worker):
        """
        Test that claim_next prioritizes jobs correctly.
        """
        # Create jobs with different priorities
        job_low_p = job_repo.create(Job(
            job_type="transcription", ytid="low-p", media_path="/path/low.mp4",
            status=JobStatus.PENDING, priority=0
        ))
        job_medium_p = job_repo.create(Job(
            job_type="transcription", ytid="medium-p", media_path="/path/medium.mp4",
            status=JobStatus.PENDING, priority=5
        ))
        job_high_p = job_repo.create(Job(
            job_type="transcription", ytid="high-p", media_path="/path/high.mp4",
            status=JobStatus.PENDING, priority=10
        ))
        job_another_medium_p = job_repo.create(Job(
            job_type="transcription", ytid="another-medium-p", media_path="/path/another_medium.mp4",
            status=JobStatus.PENDING, priority=5
        ))

        # Claim the next job
        claimed_job = job_repo.claim_next(sample_worker)

        # Expect: Highest priority job claimed first
        assert claimed_job is not None
        assert claimed_job.job_id == job_high_p.job_id
        assert claimed_job.status == JobStatus.CLAIMED
        assert claimed_job.claimed_by == sample_worker.worker_id

        # Claim again - should get the next highest priority (medium, by created_at)
        claimed_job_2 = job_repo.claim_next(sample_worker)
        assert claimed_job_2 is not None
        # Either job_medium_p or job_another_medium_p depending on creation order and exact timestamp
        # For simplicity, let's assume job_medium_p was created slightly before job_another_medium_p
        # and thus should be claimed first among same priority jobs.
        # However, a more robust test would verify both possibilities or use distinct priorities.
        # For now, we'll verify it's one of the medium priority jobs.
        assert claimed_job_2.job_id in [job_medium_p.job_id, job_another_medium_p.job_id]
        
        # To be more precise, if the creation order truly dictates secondary sort:
        if claimed_job_2.job_id == job_medium_p.job_id:
            assert job_repo.claim_next(sample_worker).job_id == job_another_medium_p.job_id
        else: # claimed_job_2.job_id == job_another_medium_p.job_id
            assert job_repo.claim_next(sample_worker).job_id == job_medium_p.job_id


