# vidops/services/analysis.py

import json
import logging
from collections import Counter
from pathlib import Path
from typing import List, Optional

from vidops.dal import VideoRepository, JobRepository, TranscriptRepository, WordRepository, FilesystemCache
from vidops.models import Job, JobStatus, Word

logger = logging.getLogger(__name__)


class AnalysisService:
    """
    Analyze transcripts/words generated by faster-whisper and persist structured outputs.
    """

    def __init__(
        self,
        video_repo: VideoRepository,
        job_repo: JobRepository,
        transcript_repo: TranscriptRepository,
        word_repo: WordRepository,
        fs_cache: FilesystemCache
    ):
        self.video_repo = video_repo
        self.job_repo = job_repo
        self.transcript_repo = transcript_repo
        self.word_repo = word_repo
        self.fs_cache = fs_cache

    def enqueue_analysis_job(
        self,
        ytid: str,
        transcript_kind: str,
        analysis_model: str,
        priority: int = 0
    ) -> Job:
        video = self.video_repo.get(ytid)
        if not video:
            raise ValueError(f"Video with ytid '{ytid}' not found.")

        transcript = self.transcript_repo.get(ytid, transcript_kind)
        if not transcript:
            raise ValueError(f"Transcript of kind '{transcript_kind}' not found for video '{ytid}'.")

        config = {
            "ytid": ytid,
            "transcript_kind": transcript_kind,
            "analysis_model": analysis_model,
            "media_path_hint": video.url,
        }

        job = Job(
            job_type="analysis",
            ytid=ytid,
            media_path=transcript.path,
            config=config,
            priority=priority,
            status=JobStatus.PENDING,
        )
        return self.job_repo.create(job)

    def process_job(self, job: Job) -> None:
        if not job.ytid:
            self.job_repo.update_status(job.job_id, JobStatus.FAILED, "Job missing ytid.")
            return

        try:
            transcript_kind = job.config.get("transcript_kind")
            if not transcript_kind:
                raise ValueError("Analysis job missing transcript_kind in config.")

            transcript = self.transcript_repo.get(job.ytid, transcript_kind)
            if not transcript or not transcript.path:
                raise FileNotFoundError(f"Transcript metadata missing for {job.ytid}:{transcript_kind}")

            transcript_path = self._hydrate_transcript(Path(transcript.path))
            transcript_content = transcript_path.read_text(encoding="utf-8")

            self.job_repo.update_status(job.job_id, JobStatus.RUNNING, "Starting analysis.")

            analysis_model = job.config.get("analysis_model", "llama3")
            summary = self._summarize_transcript(transcript_content)

            word_source = self._derive_word_source(transcript_kind)
            words: List[Word] = []
            if word_source:
                words = self.word_repo.fetch_for_source(job.ytid, word_source, limit=2000)
            top_terms = self._top_terms(words)

            analysis_payload = {
                "ytid": job.ytid,
                "model": analysis_model,
                "transcript_kind": transcript_kind,
                "summary": summary,
                "char_count": len(transcript_content),
                "word_source": word_source,
                "word_count": len(words) or transcript.word_count or 0,
                "top_terms": top_terms,
            }

            local_output = self.fs_cache.prepare_local_path(f"analysis/tmp/{job.job_id}.json")
            local_output.write_text(json.dumps(analysis_payload, indent=2), encoding="utf-8")

            relative_output = str(Path("analysis") / job.ytid / f"{job.job_id}_{analysis_model}.json")
            self.fs_cache.persist_local_artifact(
                local_output,
                relative_output,
                video_repo=self.video_repo,
                ytid=job.ytid,
                kind="analysis",
            )

            job_result = {
                "analysis_path": relative_output,
                "model": analysis_model,
                "summary_preview": summary[:200],
                "top_terms": top_terms[:5],
            }
            self.job_repo.update_status(job.job_id, JobStatus.COMPLETED, result=job_result)
            logger.info("Successfully analyzed %s (%s)", job.ytid, relative_output)

            if local_output.exists():
                local_output.unlink()

        except Exception as exc:
            error_msg = f"Analysis failed for job {job.job_id} ({job.ytid}): {exc}"
            logger.error(error_msg, exc_info=True)
            self.job_repo.update_status(job.job_id, JobStatus.FAILED, error_msg)

    def _hydrate_transcript(self, relative_path: Path) -> Path:
        """
        Ensure the transcript file exists locally and return its path.
        """
        transcript_path = self.fs_cache.get_central_path(str(relative_path))
        if transcript_path.exists():
            return transcript_path
        return self.fs_cache.pull_to_cache(str(relative_path))

    def _summarize_transcript(self, content: str) -> str:
        lines = [line.strip() for line in content.splitlines() if line.strip()]
        excerpt = " ".join(lines[:5])
        return f"{excerpt[:500]}{'...' if len(excerpt) > 500 else ''}"

    def _derive_word_source(self, transcript_kind: str) -> Optional[str]:
        if transcript_kind.startswith("words_whisper_"):
            suffix = transcript_kind.replace("words_whisper_", "")
            return f"whisper-{suffix.replace('_', '-')}"
        if transcript_kind.startswith("vtt_whisper_"):
            suffix = transcript_kind.replace("vtt_whisper_", "")
            return f"whisper-{suffix.replace('_', '-')}"
        return None

    def _top_terms(self, words: List[Word]) -> List[str]:
        stop_words = {"the", "and", "for", "that", "with", "this", "have", "from", "your", "just", "you", "but"}
        counter: Counter[str] = Counter()
        for word in words:
            token = (word.word or "").strip().lower()
            if len(token) < 3 or token in stop_words:
                continue
            counter[token] += 1
        return [term for term, _ in counter.most_common(10)]
