import csv
import logging
from pathlib import Path
from typing import List, Dict, Optional

import click

from vidops.dal import WordRepository, VideoRepository
from vidops.services import get_clipping_service

logger = logging.getLogger(__name__)

HIT_HEADERS = [
    "ytid",
    "start_sec",
    "end_sec",
    "duration_sec",
    "label",
    "phrase",
    "source",
    "media_asset_path",
]


@click.group()
def clips():
    """Manage video clips and search operations."""
    pass


@clips.command("hits")
@click.option("-q", "--query", required=True, help="Comma-separated phrases to search for.")
@click.option("--source", default="whisper-medium", show_default=True, help="Word source to search (e.g. whisper-medium).")
@click.option("--limit", type=int, default=100, show_default=True, help="Maximum hits per phrase.")
@click.option("--exact/--fuzzy", default=False, show_default=True, help="Exact token match or substring match.")
@click.option("-o", "--output", type=click.Path(), help="Optional TSV output path.")
def clips_hits(query: str, source: str, limit: int, exact: bool, output: Optional[str]):
    """Search the words table for matching phrases and emit a TSV manifest."""
    phrases = [token.strip() for token in query.split(",") if token.strip()]
    if not phrases:
        click.echo(click.style("✗ No phrases provided.", fg="red"), err=True)
        return

    repo = WordRepository()
    video_repo = VideoRepository()
    rows: List[Dict[str, str]] = []

    click.echo(f"Searching {len(phrases)} phrase(s) against source '{source}'...")
    for phrase in phrases:
        tokens = phrase.split()
        hits = repo.find_phrase_hits(tokens, source=source, limit=limit, exact=exact)
        for hit in hits:
            media_asset = video_repo.get_primary_asset(hit["ytid"], "media")
            duration = float(hit["end_sec"]) - float(hit["start_sec"])
            rows.append(
                {
                    "ytid": hit["ytid"],
                    "start_sec": f"{hit['start_sec']:.3f}",
                    "end_sec": f"{hit['end_sec']:.3f}",
                    "duration_sec": f"{max(duration, 0):.3f}",
                    "label": phrase,
                    "phrase": hit["phrase"],
                    "source": hit["source"],
                    "media_asset_path": media_asset.path if media_asset else "",
                }
            )

    if not rows:
        click.echo(click.style("No hits found.", fg="yellow"))
        return

    if output:
        dest = Path(output)
        dest.parent.mkdir(parents=True, exist_ok=True)
        with dest.open("w", encoding="utf-8", newline="") as fh:
            writer = csv.DictWriter(fh, fieldnames=HIT_HEADERS, delimiter="\t")
            writer.writeheader()
            writer.writerows(rows)
        click.echo(click.style(f"✓ Wrote {len(rows)} hits to {dest}", fg="green"))
    else:
        writer = csv.DictWriter(click.get_text_stream("stdout"), fieldnames=HIT_HEADERS, delimiter="\t")
        writer.writeheader()
        writer.writerows(rows)


@clips.command("cut")
@click.argument("hits_file", type=click.Path(exists=True))
@click.option("--priority", type=int, default=0, show_default=True, help="Job priority for enqueued clips.")
@click.option("--limit", type=int, default=None, help="Max rows to enqueue from the TSV.")
def clips_cut(hits_file: str, priority: int, limit: Optional[int]):
    """
    Enqueue clipping jobs from a TSV manifest generated by 'clips hits'.
    """
    rows = _read_hits_file(Path(hits_file))
    if limit:
        rows = rows[:limit]

    service = get_clipping_service()
    enqueued = 0
    for row in rows:
        try:
            job = service.enqueue_clip_job(
                ytid=row["ytid"],
                start_sec=float(row["start_sec"]),
                end_sec=float(row["end_sec"]),
                label=row.get("label") or "clip",
                priority=priority,
                media_relative_path=row.get("media_asset_path") or None,
            )
            click.echo(click.style(f"✓ Enqueued clip job {job.job_id} for {row['ytid']}", fg="green"))
            enqueued += 1
        except Exception as exc:
            logger.error("Failed to enqueue clip for %s: %s", row.get("ytid"), exc, exc_info=True)
            click.echo(click.style(f"✗ Failed to enqueue clip for {row.get('ytid')}: {exc}", fg="red"), err=True)

    click.echo(click.style(f"Total jobs enqueued: {enqueued}", fg="cyan"))


@clips.command("enqueue")
@click.argument("ytid")
@click.option("--start", type=float, required=True, help="Start time of the clip in seconds.")
@click.option("--end", type=float, required=True, help="End time of the clip in seconds.")
@click.option("--label", default="manual_clip", help="A label for the clip (e.g., search term, event name).")
@click.option("--priority", type=int, default=0, help="Job priority.")
@click.option("--media-asset", type=str, help="Optional relative path to the source media asset.")
def enqueue_clip_command(ytid: str, start: float, end: float, label: str, priority: int, media_asset: Optional[str]):
    """Enqueue a single video clipping job."""
    click.echo(f"Enqueuing clipping job for YTID: {ytid} from {start}s to {end}s (Label: {label}, Priority: {priority})...")

    if start >= end:
        click.echo(click.style("✗ Error: Start time must be less than end time.", fg="red"), err=True)
        return

    try:
        service = get_clipping_service()
        job = service.enqueue_clip_job(
            ytid=ytid,
            start_sec=start,
            end_sec=end,
            label=label,
            priority=priority,
            media_relative_path=media_asset
        )
        click.echo(click.style(f"✓ Clipping job enqueued: {job.job_id}", fg="green"))
    except ValueError as e:
        click.echo(click.style(f"✗ Failed to enqueue clipping job: {e}", fg="yellow"), err=True)
    except Exception as e:
        logger.error(f"Error enqueuing clipping job for {ytid}: {e}", exc_info=True)
        click.echo(click.style(f"✗ Failed to enqueue clipping job: {e}", fg="red"), err=True)


def _read_hits_file(path: Path) -> List[Dict[str, str]]:
    with path.open("r", encoding="utf-8") as fh:
        reader = csv.DictReader(fh, delimiter="\t")
        rows = [row for row in reader]
    missing = [col for col in ("ytid", "start_sec", "end_sec") if col not in reader.fieldnames]
    if missing:
        raise ValueError(f"Hits file missing required columns: {', '.join(missing)}")
    return rows
